### ISSUE TITLE
Add post title to the comments view

### ISSUE THREAD

**Issue by isamert** [thanhvg/emacs-reddigg#6]
Thanks for this amazing package! It made my morning RSS-check-routine much smoother.

Comments view does not show the title of the post itself, so there is no way to really know what the post is about just by looking at the reddigg buffer. I made this change on my local copy:

```diff
@@ -266,7 +266,8 @@ Return a value of `reddigg--cmt-list-id'"
   (with-current-buffer (reddigg--get-cmt-buffer)
     (erase-buffer)
     (insert "#+startup: overview indent\n")
-    (insert "#+title: comments\n")
+    (insert (format "#+title: comments for '%s' \n"
+                    (ht-get* (aref (ht-get* (aref data 0) "data" "children") 0) "data" "title")))
     (let ((post-id (reddigg--print-comment-1 (aref data 0))))
      (reddigg--print-comment-2 (aref data 1) "*")
      (reddigg--ensure-modes)
```

Something like this would be nice to have.

**Comment by thanhvg** [comment]
Hey glad you like it. Agree with your suggestion, can you create an PR?
